dailyfresh/apps/cart/urls.py
from .views import AddCartView, CartView, CartUpdateView, CartDelView
from django.conf.urls import url

urlpatterns = [
    url(r'^add$', AddCartView.as_view(), name='add'),
    url(r'^$', CartView.as_view(), name='info'),
    url(r'^update$', CartUpdateView.as_view(), name='update'),
    url(r'^del', CartDelView.as_view(), name='del')
]

dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from .views import Index, DetailView, ListView

urlpatterns = [
    url(r'^index$', Index.as_view(), name='index'),
    url(r'^detail/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),
    #列表详情传递三个参数 type:商品种类 page对象 sort排序方式/list/1/1?sort=''
    url(r'^list/(?P<type_id>\d+)/(?P<page_num>\d+)$', ListView.as_view(), name='list'),
]

dailyfresh/apps/orders/urls.py
from django.conf.urls import  url
from .views import OrderPayView, OrderCommitView

urlpatterns = [
    url(r'^pay$', OrderPayView.as_view(), name='pay'),
    url(r'^commit$', OrderCommitView.as_view(), name='commit')
]

dailyfresh/apps/users/urls.py
from django.conf.urls import url
from .views import RegisterView, Login, Active_View, User_Center, User_Order, User_Site, User_Logout

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^login$', Login.as_view(), name='login'),
    url(r'^active/(?P<token>.*)$', Active_View.as_view(), name='active'),
    #url(r'^active/(?P<token>.*)$', Active_View.as_view(), name='active'),
    url(r'^user$', User_Center.as_view(), name='user'),
    url(r'^order/(?P<page_num>\d+)$', User_Order.as_view(), name='order'),
    url(r'^site$', User_Site.as_view(), name='site'),
    url(r'^logout$', User_Logout.as_view(), name='logout'),
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^', include('goods.urls', namespace='goods')),
    url(r'^search', include('haystack.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='order'))
]

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django_redis import get_redis_connection
from util.mixin import MixInClass
from goods.models import GoodsSKU

class AddCartView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':1, 'msg':'请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        count = int(count)
        conn = get_redis_connection('default')
        cart_key = 'cart_%s'%user.id
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            count += int(cart_count)
        conn.hset(cart_key, sku_id, count)
        total_count = conn.hlen(cart_key)
        return JsonResponse({'res':3, 'total_count':total_count, 'msg':'添加成功'})

class CartView(MixInClass, View):
    def get(self, request):
        user = request.user
        cart_key = 'cart_%s'%user.id
        conn = get_redis_connection('default')
        cart_dict = conn.hgetall(cart_key)
        total_price = 0;
        total_count = 0
        skus = []
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price*int(count)
            sku.count = count
            sku.amount = amount
            total_count += int(count)
            total_price += amount
            skus.append(sku)
        context = {'skus' : skus,
                   'total_price' : total_price,
                   'total_count' : total_count}
        return render(request, 'cart.html', context)

class CartUpdateView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        count = int(request.POST.get('count'))
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':1, 'msg':'用户未登录'})
        cart_key = 'cart_%s'%user.id
        conn = get_redis_connection('default')
        conn.hset(cart_key, sku_id, count)
        #vals = conn.hvals
        return  JsonResponse({'res':2, 'msg':'修改成功'})

class CartDelView(View):
    def post(self, request):
        user = request.user
        sku_id = request.POST.get('sku_id')
        cart_key = 'cart_%s'%user.id
        conn = get_redis_connection()
        conn.hdel(cart_key, sku_id)
        return JsonResponse({'res' : 1, 'msg' : '删除成功'})

dailyfresh/templates/base_detail_list.html
{# 详情和列表页父模板 #}}
{% extends 'base.html' %}
{% block body %}
<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
{% block main_content %}
{% endblock main_content %}
{% endblock body %}

dailyfresh/templates/base_no_cart.html
{# 购物车、提交订单父模版 #}
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_tittle %}{% endblock page_tittle %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

dailyfresh/templates/base_static.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block tittle %}{% endblock tittle %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
	{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
	{% endblock header_con %}
	{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	{% endblock search_bar %}
	{% block body %}
	{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	{% block bottom %}
	{% endblock bottom %}
</body>
</html>

dailyfresh/templates/base_user_center.html
{# 用户中心父模板 #}
{% extends 'base_no_cart.html' %}
{% block body %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:site' %}" {% if page == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
    {% block right_content %}
    {% endblock right_content %}
</div>
{% endblock body %}

dailyfresh/templates/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block tittle %}天天生鲜-购物车{% endblock tittle %}
{% block page_tittle %}我的购物车{% endblock page_tittle %}
{% block body %}
	<div class="total_count">全部商品<em>0</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

	<form method="post" action="{% url 'order:pay' %}">
		{% csrf_token %}
		{% for sku in skus %}
		<ul class="cart_list_td clearfix"  sku_id="{{ sku.id }}">
			<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}</li>
			<li class="col06">
				<div class="num_add" >
					<a href="javascript:;" class="add fl" >+</a>
					<input type="text" class="num_show fl" value="{{ sku.count }}" sku_id="{{ sku.id }}">
					<a href="javascript:;" class="minus fl">-</a>
				</div>
			</li>
			<li class="col07">{{ sku.amount }}元</li>
			<li class="col08"><a href="javascript:;">删除</a></li>
		</ul>
		{% endfor %}


		<ul class="settlements">
			<li class="col01"><input type="checkbox" name="" checked=""></li>
			<li class="col02">全选</li>
			<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>0</b>件商品</li>
			<li class="col04"><input type="submit" value="去结算"></li>
		</ul>
	</form>
{% endblock body %}
{% block bottom %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script>

	//获取总价和总数量
	function get_total_price(){
		total_price = 0
		total_count = 0
		 $('.cart_list_td').find(':checked').each(function(){
			count = parseInt($(this).parents('ul').find('.num_show').val())
			amount = parseFloat($(this).parents('ul').children('.col07').text())
			total_price += amount
			total_count += count
		})
		//写回总价和数量
		$('.settlements').find('em').text(total_price)
		$('.settlements').find('b').text(total_count)
		$('.total_count').children('em').text(total_count)
	}
	$(function(){
		get_total_price()
	})
	error_update = true
	//更新购物车
	function update_cart(sku_id, count){
		csrf = $('input[name="csrfmiddlewaretoken"]').val()
		params = {'csrfmiddlewaretoken':csrf,
				  'sku_id': sku_id,
				  'count': count}
		$.ajaxSettings.async = false
		$.post('/cart/update', params, function(data){
			res = data.res
			if(res == 2){
				//更新成功
				//更新数量
				error_page = false
			}
		})
		$.ajaxSettings.async = true
	}

	//更新商品小计
	function update_goods_amount(count, price, th){
		if(!error_page){

			//更新商品总价
			amount = count*price
			th.parents('ul').children('.col07').text(amount.toFixed(2)+'元')
			get_total_price()
		}
	}
	//全选全不选
	$('.settlements').find(':checkbox').change(function(){
		is_checked = $(this).prop('checked')
		$('.cart_list_td').find(':checkbox').each(function(){
			$(this).prop('checked', is_checked)
		})
		get_total_price()

	})
	//勾选
	$('.cart_list_td').find(':checkbox').change(function(){
		total_list = $('.cart_list_td').length
		checked_list = $('.cart_list_td').find(':checked').length
		is_checked = true
		if(checked_list < total_list){
			is_checked = false
		}

		$('.settlements').find(':checkbox').prop('checked', is_checked)
		get_total_price()
	})
	//点击+
	$('.add').click(function(){
		//更新redis中的购物车记录
		sku_id = $(this).next().attr('sku_id')
		count = parseInt($(this).next().val())
		price = $(this).parents('ul').children('.col05').text()
		price = parseFloat(price)
		count++
		//更新购物车
		update_cart(sku_id, count)
		//更新商品数量
		$(this).next().val(count)
		//更新商品数量和小计
		update_goods_amount(count, price, $(this))
	})
	//点击-
	$('.minus').click(function(){
		//更新redis中的购物车记录
		sku_id = $(this).prev().attr('sku_id')
		count = parseInt($(this).prev().val())
		price = $(this).parents('ul').children('.col05').text()
		price = parseFloat(price)
		count--
		if(count == 0){
			count = 1
		}
		//更新购物车
		update_cart(sku_id, count)
		//更新商品数量
		$(this).prev().val(count)
		//更新商品数量和小计
		update_goods_amount(count, price, $(this))
	})
	//手动输入
	//点击记录改动之前的数量
	prev_count = 0
	$('.num_show').focus(function(){
		prev_count = parseInt($(this).val())
	})
	//失去焦点
	$('.num_show').blur(function(){
		sku_id = $(this).attr('sku_id')
		count = $(this).val()
		if(isNaN(count) || count.trim().length==0 || parseInt(count)<=0){
			$(this).val(prev_count)
			return
		}
		count = parseInt(count)
		price = parseFloat($(this).parents('ul').children('.col05').text())
		//更新购物车
		update_cart(sku_id, count)
		//更新商品数量
		$(this).val(count)
		//更新商品数量和小计
		update_goods_amount(count, price, $(this))
	})
	//删除
	$('.cart_list_td').children('.col08').children('a').click(function(){
		sku_id = $(this).parents('ul').attr('sku_id')
		//alert(sku_id)
		csrf = $('input[name="csrfmiddlewaretoken"]').val()
		params = {'sku_id':sku_id,
				  'csrfmiddlewaretoken':csrf}
		ul = $(this).parents('ul')
		error_page = true
		$.post('/cart/del', params, function(data){
			if(data.res == 1){
				ul.remove()
				get_total_price()
			}
		})
	})
</script>
{% endblock bottom %}

dailyfresh/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
	<title>{% block tittle %}天天生鲜-首页{% endblock tittle %}</title>
	{% block topfiles %}
	<script type="text/javascript" src="js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="js/slide.js"></script>
	{% endblock topfiles %}
	{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %}
			<li><a href="{% url 'goods:list' type.id 1 %}" class="{{type.logo}}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for goods in index_goods_banner %}
				<li><a href="#"><img src="{{goods.image.url}}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for goods in index_promotion_banner %}
			<a href="#"><img src="{{goods.image.url}}"></a>
			{% endfor %}
		</div>
	</div>
	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{type.name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for goods in type.tittle_goods_banner %}
				<a href="{% url 'goods:detail' goods.sku.id %}">{{ goods.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{type.image.url}}"></div>
			<ul class="goods_list fl">
				{% for goods in type.image_goods_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' goods.sku.id %}">{{ goods.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' goods.sku.id %}"><img src="{{ goods.sku.image.url }}"></a>
					<div class="prize">¥ {{ goods.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}

	{% endblock body %}
	{% block bottom %}
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
	{% endblock bottom %}
</body>
</html>

dailyfresh/templates/list.html
{% extends 'base.html' %}
	{% block tittle %}天天生鲜-商品列表{% endblock tittle %}
	{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}"></a>{{ type.name }}</li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1 %}">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for goods in new_type_goods %}
					<li>
						<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for goods in page %}
				<li>
					<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.price }}</span>
						<span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if page.has_previous %}
				<a href="{% url 'goods:list' type.id page.previous_page_number %}?sort={{sort}}"><上一页</a>
				{% endif %}
				{% for num in pg.page_range %}
				<a href="{% url 'goods:list' type.id num %}?sort={{sort}}" {% if page_num == num %}class="active"{% endif %}>{{ num }}</a>
				{% endfor %}
				{% if page.has_next %}
				<a href="{% url 'goods:list' type.id page.next_page_number %}?sort={{sort}}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endblock body %}

dailyfresh/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block tittle %}
天天生鲜-登录
{% endblock tittle %}
{% block header_con %}
{% endblock header_con %}
{% block search_bar %}
{% endblock search_bar %}
{% block body %}
<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{%static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{username}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{checked}}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

dailyfresh/templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
	{% block tittle %}天天生鲜-提交订单{% endblock tittle %}

{% block page_tittle %}提交订单{% endblock page_tittle %}
	{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		{% for addr in addrs %}
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="addr" value="{{ addr.id }}"  {% if addr.is_default %}checked{% endif %}>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
		</dl>
		{% endfor %}
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>
	{% csrf_token %}
	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		{% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ trans_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn" sku_ids="{{ sku_ids }}">提交订单</a>
	</div>	
	{% endblock body %}
	{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function(){
			addr_id = $('input[name="addr"]:checked').val()
			pay_style = $('input[name="pay_style"]:checked').val()
			sku_ids = $(this).attr('sku_ids')
			csrf = $('input[name="csrfmiddlewaretoken"]').val()
			params = {'addr_id':addr_id,
					  'pay_style':pay_style,
					  'sku_ids':sku_ids,
					  'csrfmiddlewaretoken':csrf}
			$.post('/order/commit', params, function(data){
				if(data.res == 2){
					localStorage.setItem('order_finish',2);
                    $('.popup_con').fadeIn('fast', function() {

                        setTimeout(function(){
                            $('.popup_con').fadeOut('fast',function(){
                                window.location.href = '{% url 'user:order' 1 %}';
                            });
                        },3000)
                        });
				}
			})
		})
	</script>
	{% endblock bottom %}